spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: primihub
      url: jdbc:mysql://mysql.primihub.svc.cluster.local:3306/fusion_prod?characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
      password: primihub@123
      filter:
        config:
          enabled: true
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 30000
      validationQuery: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: false
      filters: stat,wall,slf4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      time-between-log-stats-millis: 300000
logging:
  level:
    root: info
